### ISSUE TITLE
Release 4.2 reproducibly crashes

### ISSUE THREAD

**Issue by rh63** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#39]
Hi Ceiridge,

currently, there's no way for me to get your patcher to work on W10 1909 or 2004 when trying to patch Edge. Start of the program is completely normal, but the instant I touch the _(Re-)Install_ button, the process freezes. Therefore not even a log entry is available. This is all I get:

![image](https://user-images.githubusercontent.com/65854998/88801592-33af6680-d1aa-11ea-9824-07bb55db7db8.png)

[The title bar text in parentheses (**_Keine Rückmeldung_**) is the German equivalent to **_Not responding_**]

Afterwards all I can do is to kill the process... Needless to say that the patches are not applied.

BTW: I tried that on several PCs (the above screenshot is from a 1909 machine) - the result is always the same.  :(   Is there a special requirement for your Patcher?

**Comment by Ceiridge** [comment]
This is because some processes don't unload the dll injected with Windows hooks. Because of this, the file is locked and can't be written to.
The release 4.2 should have fixed this by sending out messages to every process, but it seems to not affect some processes.

Or is this the first time you tried to install it (version 4.0+)?

**Comment by rh63** [comment]
No, I'm using your program since ~3.4 (I'm not quite sure, but it must have been around April).

**Comment by Ceiridge** [comment]
Then it's because of the bug I mentioned.
What you can do as a temporary fix: Click Uninstall All > Download Process Hacker x64 > Find Handles or DLLS > Search for "PatcherDll.dll" > Look at the process list > Find each process (use the PID) > Click on the Modules tab > Search for the ChromePatcherDll.dll module > Right click & Unload > Reinstall the patcher

**Comment by rh63** [comment]
Ok. I'll try that as soon as I'm back at my desk.

**Comment by rh63** [comment]
Well, the test is done (although I used _Process Explorer_ instead) and you're right; the workaround did the trick. :)

Strangely enough, the culprit is a part of my MFP driver! It's called **_HPNetworkCommunicatorCom.exe_** and is the endpoint for scanning from the MFP device to a PC. Why it interferes with _ChromePatcherDll.dll_ is a complete mystery to me.

**Comment by Ceiridge** [comment]
It's because the patcher dll is injected with Windows hooks, so it is loaded before Chrome actually starts to load. Windows injects this dll into every process with the same session and lower or equal permissions on a window/start event.
What I was worried about are anticheats, but they all block the Windows hook for the game processes anyway and using Windows hooks is a common technique, so it shouldn't be a problem.

**Comment by rh63** [comment]
Thanks for the explanation!

Does this mean, you can do anything about it in your Patcher or do I have to keep using the workaround? Would be no big deal, now that I know which process to kill.. ;)

**Comment by Ceiridge** [comment]
You don't need to kill the entire process - unloading the module with Process Hacker is enough - and I'm still searching for a good and easy fix, but it will be patched in the future

**Comment by rh63** [comment]
Yeah, I know. :) But it's a lot quicker just killing the process in the task manager. I don't use this kind of scan function anyway.

I'm looking forward to your "good and easy fix"! ;)

**Comment by Ceiridge** [comment]
1453b9be0e43d5c89a00ff463f2acc073dba61df
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases

**Comment by rh63** [comment]
You did it! :) 

Nice trick with the unique DLL names...  Not even HP can interfere this way! ;)
