### ISSUE TITLE
Bug Report: Not working with Avast Secure Browser Chromium

### ISSUE THREAD

**Issue by Andrei-drugon** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#48]
The Patcher was working with **Avast Secure Browser Chromium** until version 4.3.0 , now it doesn't work anymore. 
Any help?

Thanks

**Comment by Ceiridge** [comment]
Could you please send these log files located at these paths, so that I can investigate the issue further:
`C:\Windows\Temp\ChromePatcherDll.log`
`C:\Windows\Temp\ChromePatcherDllErr.log`
`C:\Windows\Temp\ChromePatcherInjector.log`

**Comment by jiurou** [comment]
I don't use it anymore
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ceiridge<mailto:notifications@github.com>
发送时间: 2020年9月27日 20:40
收件人: Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher<mailto:Chrome-Developer-Mode-Extension-Warning-Patcher@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher] Bug Report: Not working with Avast Secure Browser Chromium (#48)


Could you please send these log files located at these paths, so that I can investigate the issue further:
C:\Windows\Temp\ChromePatcherDll.log
C:\Windows\Temp\ChromePatcherDllErr.log
C:\Windows\Temp\ChromePatcherInjector.log

―

**Comment by Andrei-drugon** [comment]
I've attached also ChromePatcherInjectorErr.log, in case you may need it. 
Thanks!

[ChromePatcherDll.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5288605/ChromePatcherDll.log)
[ChromePatcherDllErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5288606/ChromePatcherDllErr.log)
[ChromePatcherInjector.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5288607/ChromePatcherInjector.log)
[ChromePatcherInjectorErr.log](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/files/5288608/ChromePatcherInjectorErr.log)

**Comment by Ceiridge** [comment]
Are you using an outdated version?

**Comment by Andrei-drugon** [comment]
Currently I'm using version 4.3.0 because is the only one working.
I tried using newer version and the latest ( version 4.5.1 ) but none seems working.

**Comment by Ceiridge** [comment]
What operating system are you on?

**Comment by Andrei-drugon** [comment]
Windows 64-bit

**Comment by Ceiridge** [comment]
And which version?

**Comment by Andrei-drugon** [comment]
10 Home edition

**Comment by Ceiridge** [comment]
Then you should always be using the latest version. Does the patcher work for other browsers like Chrome or Brave?

**Comment by Andrei-drugon** [comment]
Yes, it does.

**Comment by Andrei-drugon** [comment]
> Then you should always be using the latest version. Does the patcher work for other browsers like Chrome or Brave?

I tried using the latest version to patch Avast Secure Browser Chromium but it doesn't work, the Extension Warning still appears.

**Comment by Ceiridge** [comment]
Then apparently the patcher is not compatible with the Avast browser and it won't be supported in the future because of a small user count.
(Also, Avast is more a spyware than an antivirus)
