### ISSUE TITLE
Crashes if Bug Report: 

### ISSUE THREAD

**Issue by AJolly** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#58]
Crashes silently if the Windows Desktop Runtime is not installed.
Theres an error message in the windows event log, but unless you check there, you have no idea why this failed to run.

**Comment by Ceiridge** [comment]
A warning that the runtime is missing is shown for a split second in the appearing console. I will think of a good solution

**Comment by Ceiridge** [comment]
It would be required to patch the .NET 5 runtime apphost or to recompile it just to display the message box, because the executable is intentionally compiled with a console subsystem, so that it can be started as a GUI and console.
Instead, I'm now recommending to download it (also with a readme file).

**Comment by AJolly** [comment]
Seems perfectly reasonable if its in the readme. (Running it from the console did not display an error message)
