### ISSUE TITLE
Remove other entries in chrome context menu. That don't depend on a flag inside chrome 

### ISSUE THREAD

**Issue by cpuuntery** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#63]
**The first thing that I want to say. Is to thank the developer for solving issue** #62 so quickly 
But that got me thinking, is it possible to remove other entries in chrome context menu like 
[![fix.png](https://i.postimg.cc/zvhF79M6/fix.png)](https://postimg.cc/p52jX1PJ)
print
cast 
The different thing about print and cast is that they don't depend on a flag inside chrome, I think that the existent of a flag make it easy to debug and find the memory address to patch. So if it is possible to remove them. I would be very happy

**Comment by Ceiridge** [comment]
This patcher exists to remove annoyances and I don't see how these two options could annoy anyone.
I also wouldn't want to add many features most users won't use. Unfortunately, it also takes a lot of time to patch something out, because it has to be found in the huge Chromium source code at first, then a function or similar has to be found that can be easily patched out to disable the unwanted feature and finally, I have to look that function up in the latest chrome symbol file, open that address in a disassembler and create a byte pattern.

**Comment by cpuuntery** [comment]
@Ceiridge 
Thank you for the reply, I understand your reasoning. 
But if possible. Can you patch this flag [copy-link-to-text] ?
[![copy-link-text.png](https://i.postimg.cc/0y2kXhP6/copy-link-text.png)](https://postimg.cc/VdpPdGS1)
I know what are you going to say. But hear me out.
The feature to directly link to specific text on a page is not supported on all websites. And while it is a flag now, we all know that Google love to **deprecate** the flags in future version.
But if you think the feature is important and loved by all the user of any Chromium based browsers. And that you will not bother to figure out how to patch. **That is completely fine by me**.


And speaking of features most users won't use.
**I want to thank you a lot** about the [Disable Elision] feature
it was a real lifesaver in Chrome 79 to 82
But since Chrome 83 you can enable full URL without patching chrome 
[![82fdY.png](https://i.postimg.cc/Z53cgsHS/82fdY.png)](https://postimg.cc/5X4LQ3D7)
for more info 
https://superuser.com/a/1498561

And after reading my comment, **it is completely fine by me**. If you think my request is not worth it or unreasonable and due to that you will close this issue 

**And lastly I want to thank you very very very much for this tool**

**Comment by Ceiridge** [comment]
@cpuuntery I have completely missed the apparently new context menu option "Copy link to text" and never read it before and actually wanted to get rid of it, because now the context menu is larger than usual for me. But now that I have read it, I'm not sure if you want me to patch it out or somehow make it permanent, because this is a very useful feature in my opinion so that I even coded a Tampermonkey script to add such a button the the context menu since Google used it in their links. So I'm not going to patch something out that I even intentionally added manually without even knowing that it already exists.

I also know about the "Always show full URLs" option, but I still prefer my patch, because as far as I know, some other Chromium browsers do not save if you enabled that option and maybe it will be removed again in the future.

Removing things out of the context menu is harder than usual, because most of the options do not call a function to check if it should be displayed (the QR code thing luckily was an exception), and I don't want to modify the body of that one function that adds all the options.

I hope I haven't been too harsh in my responses (because it has felt like that for me when writing them) and I really appreciate you liking my tool!

**Comment by cpuuntery** [comment]
@Ceiridge 
**You are not harsh at all.** And I understand your reasoning, plus removing print and cast was something nice to have. **So I am completely fine with your decision**.

My plan for chrome once google enforce Manifest v3, not only ad-blocker extensions will get affected. User script extensions like Tampermonkey will get affected as well.
But, I use Violentmonkey because it is an open source, and it also will get affected.

My plan to use the last version of chromium that support Manifest v2 and one nice thing about chromium it does not come with the annoying auto update

[this website contains chromium builds for windows, among other operating systems.](https://chromium.woolyss.com/)

I know you may think I digressed a lot, but this is my last comment before closing this issue.
