### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SubGi** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#66]
Hi. This patcher works great. But the problem is after patching, edge opens very slowly every-time i open it. Is there a way to whitelist my extension without using this patcher ?. I use windows 10 Home.

**Comment by Ceiridge** [comment]
Thanks! Yes, the patcher adds some seconds of delay, because it has to search the chrome.dll in memory (about 200 MB in size) and search for patterns. I really should optimize it in the future, because it shouldn't take that long at all if done correctly.
There is a way to whitelist an extension id if you manually install your packed .crx file with developer mode enabled: https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::ExtensionInstallWhitelist

**Comment by SubGi** [comment]
Thanks for this fast reply. I actually tried many methods to whitelist my extension. But i cannot find that directory in my computer.
If you can help I can try one last time else I will be more than happy to wait for the optimized  patch. Thank You.

**Comment by Ceiridge** [comment]
1. Open regedit.exe
2. Navigate to `HKCU\Software\Policies\Google\Chrome` (If it does not exist, create the registry keys until you can navigate to that path)
3. Create a new registry sub key named `ExtensionInstallWhitelist`
4. In there, add a new string value with your extension id in it.


This is what you should do summarized of what I sent you before

**Comment by Ceiridge** [comment]
I have now implemented SIMD AVX2 and multithreading for searching the patterns. For me, it now patches 4 different patches in under 100 ms.
f05162f72d9302548ee4c853c45f13c061becc8c
The release should be ready in some minutes.
