### ISSUE TITLE
Feature Request:  Remove sync your profile popup warning

### ISSUE THREAD

**Issue by eix128** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#68]
Hi , i want to remove sync your profile warning on edge browser.
If also chrome also have.
How to disable this popup warning ?
I did not find any way to remove this warning popup
![syncYourProfile](https://user-images.githubusercontent.com/1905952/129480209-b4c93cc7-8d88-404b-9309-22da598da0c3.png)

**Comment by Ceiridge** [comment]
How often have you seen that popup or did it disappear forever after clicking on _Got it_?
If it appears too often, can you try signing out of your Microsoft account in Edge (as stated in the popup: Settings > Profiles)?

**Comment by eix128** [comment]
I am using Selenium automation.
I cant disable manually need some automated way to do it on Selenium Java

**Comment by Ceiridge** [comment]
You can try some of these command line arguments to disable MS Edge Sync (or you just use Chrome?).
I would try out each of those:
`--disable-sync`
`--bwsi`
`--guest`
`--incognito`

or you could try changing this registry key: https://websiteforstudents.com/how-to-disable-microsoft-edge-profile-sync/#:~:text=After%20saving%20the%20DWORD%20above

**Comment by eix128** [comment]
Thanks , "--guest" flag  solved the problem

**Comment by eix128** [comment]
Well sorry but , with "--guest" it disables saving cookies and session data to profile folder.
I want popup disabled with saving cookies and session data save enabled.

**Comment by Ceiridge** [comment]
Have you tried the other methods I listed?

**Comment by eix128** [comment]
Yes , none of them worked.
Any solution to make patch with Chrome-Developer-Mode-Extension-Warning-Patcher ?
Maybe you can make some patch for that

"--guest" flag disables the popup but it also disables saving cookies and session data to profile folder.
Maybe with that flag

**Comment by eix128** [comment]
Checkout
https://github.com/MicrosoftEdge/MSEdge

**Comment by Ceiridge** [comment]
I'm not going to patch that, because asides from the patcher being mainly targetted for Chrome, the code for the profile login screen in Edge is not open source (your Github link was only a statement by Microsoft) and this makes it harder to create a patch.
Additionally, I'm not sure if they provide full PDB files (they probably have some minimal ones lying on Microsoft's symbol server).
So it would definitely require lengthy reverse engineering because of these two reasons.

You can still log out of your Microsoft account in the Settings app of Windows or you can use another browser with Selenium
