### ISSUE TITLE
Edge of recent version can use a less intrusive patch

### ISSUE THREAD

**Issue by YijunYuan** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#75]
Compared to patching the .dll file, [this answer](https://stackoverflow.com/a/70374300/4182574) on StackOverflow seems to be less intrusive. It delays the Develop Mode warning to thousands of years later, which seems to be more reliable.

**Comment by Ceiridge** [comment]
Thanks, I will pin your issue.
Chromium seems to have accidentally? disabled the extension warning, except for Edge, which has an option to hide it for a certain duration. It's probably much more reliable (and faster) in this case than patching the DLL on every start and it also survives updates with less issues.
I won't implement this in this patcher, because it has lost its original purpose due to the changes I just mentioned except for the other available patches, which still require in-memory scanning and patching anyway.
