### ISSUE TITLE
How do I disable/uninstall this???????

### ISSUE THREAD

**Issue by theridon** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#80]
I don't see any instructions. Thank you.

**Comment by Ceiridge** [comment]
Do these steps in order to uninstall
1. Download the [latest Chrome patcher installer](https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/releases) or run the installer you used
2. Select all the browser you have installed the patcher on
3. In the tab `Install Patches`, there is an *Uninstall* button
