### ISSUE TITLE
Bug Report: Unable to run offline

### ISSUE THREAD

**Issue by bananakid** [Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher#88]
**Describe your problem in one sentence:**
Patcher is not able to patch without Internet connection

**Name the affected patch/problem (if available)**
All

**Your used browser**
Microsoft Edge 100.0.1185.50

**Longer description (optional)**
I need to run this offline. I downloaded and copied patterns.xml to patcher's folder. However error message appears when patcher is executed. Error says an error occurred trying to fetch new patterns. I don't need it to fetch patterns.xml, I already have the file.

**Comment by Ceiridge** [comment]
I won't fix this, because this is a feature that keeps it up to date.

But there is a way to manually do it: You need to place the patterns.xml file into this location `%temp%\chrome_patcher_patterns.xml` and then it will work.
This can be seen here: https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher/blob/873968d8bb7b8498b2a981282e6388648b8087cd/ChromeDevExtWarningPatcher/Patches/BytePatchManager.cs#L29
If you don't have access to the temp folder, you can potentially work around this by starting the patcher with different environment variables, such as overriding the %temp% or TEMPDIR environment variable.

**Comment by bananakid** [comment]
@Ceiridge, thanks for explanation, %temp% workaround is alright! Probably worth mentioning in readme.md.
